# conda env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - matplotlib
  - numpy
  - pandas
  - pip
  - plotly
  - pyprojroot
  - python=3.11.3
  - seaborn
  - networkx
  - scipy
  - igraph
  - pyvis
  - graph-tool
